In [1]:
!pip install wget
import wget
import zipfile
wget.download('https://raw.githubusercontent.com/Call-for-Code/Spot-Challenge-Wildfires/main/data/Nov_10.zip', 'Nov_10.zip')
zip_handle = zipfile.ZipFile("Nov_10.zip")
zip_handle.extractall()
import pandas as pd
import numpy as np

Collecting wget
  Downloading https://files.pythonhosted.org/packages/47/6a/62e288da7bcda82b935ff0c6cfe542970f04e29c756b0e147251b2fb251f/wget-3.2.zip
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-cp37-none-any.whl size=9681 sha256=9107e4dcc781b6c576ff5215e5831999ee17500b2db4ac3a5d3c129bb2750af0
  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

In [2]:
file_land = "/content/Nov_10/LandClass.csv"
print("Reading file: '{}'".format(file_land))
df_land = pd.read_csv(file_land)
print("Loaded...")

df_land

Reading file: '/content/Nov_10/LandClass.csv'
Loaded...

  Region  Shrubs  ...  Open forest, unknown definitions  Open sea
0    NSW     6.2  ...                              10.3       0.1
1     NT    18.1  ...                               9.3       0.5
2     QL     9.5  ...                              11.0       0.3
3     SA    24.1  ...                               5.3       0.6
4     TA     0.7  ...                               7.2       3.0
5     WA    31.3  ...                               8.7       0.8
6     VI     1.4  ...                               5.2       0.9

[7 rows x 15 columns]

In [3]:
df_land_class = df_land.sort_values(by='Region').T.copy()
df_land_class.rename(columns=df_land_class.iloc[0], inplace=True)
df_land_class.drop(['Region'], axis=0, inplace=True)
df_land_class = df_land_class.astype(np.float)
df_land_class = df_land_class.rename_axis('Land Type').reset_index()
df_land_class

                                            Land Type   NSW  ...    VI    WA
0                                              Shrubs   6.2  ...   1.4  31.3
1                               Herbaceous vegetation  43.6  ...  35.0  43.5
2   Cultivated and managed vegetation/agriculture ...  13.0  ...  23.3   5.6
3                                    Urban / built up   0.3  ...   1.0   0.0
4                            Bare / sparse vegetation   0.2  ...   0.1   1.0
5                              Permanent water bodies   0.2  ...   0.6   0.4
6                                  Herbaceous wetland   0.1  ...   0.3   0.0
7                Closed forest, evergreen, broad leaf  14.7  ...  23.9   1.2
8                 Closed forest, deciduous broad leaf   6.8  ...   3.8   2.4
9                              Closed forest, unknown   0.3  ...   0.3   0.2
10                  Open forest, evergreen broad leaf   0.5  ...   1.5   0.1
11                  Open forest, deciduous broad leaf   3.7  ...   2.7   4.8
12                   Open forest, unknown definitions  10.3  ...   5.2   8.7
13                                           Open sea   0.1  ...   0.9   0.8

[14 rows x 8 columns]